name: Cypress Tests

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # 👇 instala librerías necesarias para Chrome/Electron
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          libgtk2.0-0 \
          libgtk-3-0 \
          libgbm-dev \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          xauth \
          xvfb

      - name: Install
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # 👈 fuerza chrome
          headed: false # 👈 modo headless
          config: baseUrl=https://testreservas.teayudo.com.bo
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
